# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6.0.x'
  inputs:
    version: 6.0.x
    includePreviewVersions: true

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.x'
  inputs:
    versionSpec: 5.x
    checkLatest: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: 'Build MVC'
  inputs:
    command: build
    projects: 'RssFeeder.Mvc/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: 'Build Crawler'
  inputs:
    command: build
    projects: 'RssFeeder.Console/*.csproj'
