name: RssFeeder Local Deployment

env:
  DOTNET_VERSION: '10.0.x'                 # set this to the .NET Core version to use
  
on:
  push:
    branches:
      - "master"
    paths:
      - 'RssFeeder.Console/**'
  workflow_dispatch:
  
permissions:
  contents: read
  
jobs:
  backup-config:
    name: Backup Configs
    runs-on: self-hosted
    steps:
      - name: Run Backup Script
        run: /ps/Backup-FeedConfigs.ps1 -deployFolder "${{ secrets.LOCAL_DEPLOY_FOLDER }}"

  deploy-local:
    name: Deploy to Local
    runs-on: self-hosted
    needs: backup-config
    steps:
      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Publish the updated app
        run: dotnet publish ./RssFeeder.Console/RssFeeder.Console.csproj /p:PublishProfile=FolderProfile /p:DeployFolder="${{ secrets.LOCAL_DEPLOY_FOLDER }}"
